import pathlib,json,sys,hashlib,numpy as np,torch
from research_log.T059I.core import tensor_only
out=pathlib.Path(sys.argv[1]);r=json.loads((out/'result.json').read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();torch.set_num_threads(1)
for n,h in r['inputs_before'].items():assert sha(pathlib.Path(n))==h==r['inputs_after'][n]
assert sha(out/'candidates.pt')==r['candidate_marker']['sha256'] and sha(out/'oracle_rows.pt')==r['oracle_rows_sha256'];pool=torch.load(out/'candidates.pt',map_location='cpu',weights_only=True);rows=torch.load(out/'oracle_rows.pt',map_location='cpu',weights_only=True)
root=pathlib.Path('/home/wenchang/asdasdsad/wjq/TTIE');G=root/'runs/20260918-050302-ttie-t059g-nn/artifacts/T059G';I=root/'runs/20260918-073334-ttie-t059i-five/artifacts/T059I';m=torch.load(G/'maps.pt',map_location='cpu',weights_only=True);five=torch.load(I/'maps.pt',map_location='cpu',weights_only=True);pt=pool['target'].numpy();px=pool['x'].double().numpy();pi=pool['image'].numpy();pg=pool['global_index'].numpy();assert np.all(np.diff(pg)>0);metrics={};maxerr={}
for s in ['train','heldout']:
 target,_=tensor_only(G/'evaluation_rows.pt',s,'target');y=target.numpy();qx=m[s]['x'].double().numpy();qi=m[s]['image'].numpy();saved=rows[s];errors=0.
 for start in range(0,len(y),64):
  yy=y[start:start+64];allowed=(qi[start:start+len(yy),None]!=pi[None,:]) if s=='train' else np.ones((len(yy),len(pt)),bool);e=np.abs(pt[None,:]-yy[:,None]);loss=np.where(e<1,np.float32(.5)*e*e,e-np.float32(.5));loss[~allowed]=np.inf;idx=loss.argmin(1);v=loss[np.arange(len(idx)),idx];assert np.array_equal(idx,saved['index'][start:start+len(idx)].numpy()) and np.array_equal(v,saved['loss'][start:start+len(idx)].numpy());assert np.array_equal((loss==v[:,None]).sum(1),saved['scalar_minimum_tie_count'][start:start+len(idx)].numpy())
  d=np.square(qx[start:start+len(yy),None,:]-px[None,:,:]).sum(-1);chosen=d[np.arange(len(idx)),idx];rank=1+(((d<chosen[:,None])|((d==chosen[:,None])&(pg[None,:]<pg[idx,None])))&allowed).sum(1);count=allowed.sum(1);assert np.array_equal(rank,saved['distance_rank'][start:start+len(idx)].numpy()) and np.array_equal(count,saved['candidate_count'][start:start+len(idx)].numpy());assert np.allclose((rank-1)/(count-1),saved['distance_percentile'][start:start+len(idx)].numpy(),rtol=1e-14,atol=1e-14)
  lo=np.where(allowed,pt[None,:],np.inf).min(1);hi=np.where(allowed,pt[None,:],-np.inf).max(1);assert np.array_equal((yy>=lo)&(yy<=hi),saved['in_global_range'][start:start+len(idx)].numpy());assert np.array_equal((idx[:,None]==five[s]['index'][start:start+len(idx)].numpy()).any(1),saved['in_five'][start:start+len(idx)].numpy());actual=saved['distance'][start:start+len(idx)].numpy();assert np.allclose(chosen,actual,rtol=1e-12,atol=1e-12);errors=max(errors,float(np.abs(chosen-actual).max()))
 h=float(saved['loss'].mean());assert h==r['statistics'][s]['global_oracle_huber'];metrics[s]=h;maxerr[s]=errors;assert torch.equal(saved['global_index'],pool['global_index'][saved['index']]);assert not (saved['image']==m[s]['image']).any()
limit=.07650849781930447;classification='global inner-train scalar support is inadequate even on train-LOO under the fixed source pool' if metrics['train']>limit else 'marginal scalar support exists in the fixed inner-train pool; the unresolved failure is localization/conditioning of that support rather than absence of scalar values' if metrics['heldout']<=limit else 'inner-held scalar targets are inadequately supported even by the global fixed inner-train scalar pool; 28-D locality alone cannot explain the transfer failure';assert classification==r['classification'];assert r['candidate_marker']['persisted_utc']<r['held_scalar_opened_utc'];assert all(v==0 for v in r['counters'].values())
z=dict(verification='PASS',independent_classification=classification,global_oracle_huber=metrics,all_5886_choices_losses_ties_exact=True,all_candidate_counts_range_five_membership_and_distance_ranks_verified=True,max_distance_error=maxerr,result_sha256=sha(out/'result.json'));(out/'verification.json').write_text(json.dumps(z,indent=2));print(json.dumps(z))
