"""Build the T025-A review report from completed, independently aggregated evidence."""
import json
from pathlib import Path
r=Path('research_log'); out=r/'remote_runs/20260914-075823-ttie-t025a-oracle/artifacts/REFERENCE_ORACLE_ONLY'
s=json.loads((out/'independent_summary.json').read_text()); audit=json.loads((out/'independent_aggregation.json').read_text());done=json.loads((out/'completion.json').read_text());config=json.loads((out/'config.json').read_text())
assert audit['passed'] and done['pairs']==100 and done['all_oracle_mse_nonworse']
lines=['# T025-A: frozen Region2 reference-oracle reachability','','**REFERENCE_ORACLE_ONLY — oracle ceiling measured.** Exactly100 frozen validation pairs completed both fixed starts (200 starts,100000 Adam updates) on NVIDIA RTX A6000. Every selected start reproduced the accepted T022-C result within tolerance, every oracle MSE was non-worse, and independent aggregation passed. No official-test image was opened; no deployable module, model weight, gate or action bound changed.','','This is a non-deployable reference-assisted diagnostic. The fixed two-start local search demonstrates reachable quality in the existing action family; it does not certify the global optimum or an absolute mathematical upper bound. No oracle state or reference-derived quantity is fed into deployable TTT.','','## Measured validation quality','','| Output | Mean PSNR dB | Median PSNR dB | Mean RGB-SSIM | Median RGB-SSIM |','|---|---:|---:|---:|---:|']
for name,label in [('raw','Raw input'),('selected','Accepted T022-C'),('oracle','REFERENCE_ORACLE_ONLY')]:
 a=s['aggregates'][name];lines.append(f"| {label} | {a['psnr']['mean']:.9f} | {a['psnr']['median']:.9f} | {a['ssim']['mean']:.9f} | {a['ssim']['median']:.9f} |")
lines+=['','| Oracle minus T022-C | Mean | Median | p10 | p90 |','|---|---:|---:|---:|---:|']
for m in ['psnr','ssim']:
 a=s['paired_oracle_minus_T022C'][m];lines.append(f"| {m} | {a['mean']:+.9f} | {a['median']:+.9f} | {a['p10']:+.9f} | {a['p90']:+.9f} |")
lines+=['',f"PSNR improves by more than1e-6 on {s['images_psnr_improved']}/100 images. SSIM decreases on {s['images_ssim_worse']}/100; SSIM was scored after optimization and never enters the MSE objective or state selection.",'','## Fixed search and state provenance','','The original deterministic split SHA256 is `'+config['split_sha256']+'`. Reused T022-C run: `20260914-042925-ttie-t022c-ev2`. Its decision/output/trajectory hashes are checked against the existing freeze receipt per image. Each gate remains frozen; the reconstructed action box must equal the saved box. Native RGB600x400, unchanged hard Region2 rendering, active dark EV0..2, bright EV-.5..0, gamma.8..1.25, inactive identity.','',f"Seed{config['seed']}; exactly{config['updates_per_start']} Adam updates per identity/selected start, lr{config['lr']}, default betas/epsilon, no scheduler. Float64 full-frame MSE accumulation through the accepted float32 renderer. Retain earliest minimum at steps0..500 and lower-MSE start; identity resolves exact inter-start ties. No additional starts, schedule changes or bounds tuning.",'','## Start and step statistics','',f"Start wins: `{json.dumps(s['start_wins'],sort_keys=True)}`.",'']
for k,v in s['step_histograms'].items():lines.append(f'- {k}: `{json.dumps(v,sort_keys=True)}`')
lines+=['','A winning best state at step500 means the fixed search was still finding its lowest observed MSE at the budget endpoint; it is not proof of convergence. This task does not add steps or restarts in response.','','## Bound saturation','','Tolerance is1e-6 in physical coordinates. Active-only denominators exclude the trivially fixed identity coordinates; all-coordinate denominators are also reported in the JSON. The +2 EV endpoint uses the unchanged2*tanh(raw) map and can be approached without being counted as saturated at this tight tolerance.','',f"Active regions: {s['active_regions']}; inactive: {s['inactive_regions']}; total400.",'','| Parameter bound (active only) | Count | Denominator | Fraction |','|---|---:|---:|---:|']
for k,v in s['saturation'].items():
 if k.endswith('_active_count'):lines.append(f"| {k} | {v['count']} | {v['denominator']} | {v['fraction']:.6f} |")
lines+=['','## Checks, execution and interpretation','',f"Maximum selected-output reproduction error: {s['reproduction_max_abs']:.12g} (tolerance1e-6); physical-grid and PSNR/SSIM reproduction checks also pass. All100 oracle MSE values satisfy non-worse tolerance1e-10. All200 starts execute500 updates and all outputs/metrics/states are finite. Independent CSV/JSON aggregation passes without importing optimization code.",'',f"Mean per-image runtime{ s['runtime_seconds']['mean']:.3f}s; median{ s['runtime_seconds']['median']:.3f}s. Job `20260914-075823-ttie-t025a-oracle`, release `20260914-075755-ttie-t025a-oracle`, source `04e436dbefad747a562fd68faacecaf5d90006c9`. Actual CUDA computation and full run pass despite the server NVML monitoring warning. Baseline3tests and focused oracle1test passed before launch.",'',f"The measured mean gap is {s['paired_oracle_minus_T022C']['psnr']['mean']:+.4f}dB / {s['paired_oracle_minus_T022C']['ssim']['mean']:+.6f} RGB-SSIM. This quantifies useful states found outside the accepted learned trajectory under the same gate/action family. The absolute oracle quality, paired distribution, boundary use and endpoint-step counts must also inform whether the state family remains limiting. No binary promotion claim or SOTA claim is made; the research lead chooses the next task.",'','## Evidence locations','','- `research_log/T025A_fixed_protocol.md`, `T025A_reuse.json`, `T025A_local_checks.json`, launch/deployment receipts: fixed settings and exact reuse.','- `research_log/remote_runs/20260914-075823-ttie-t025a-oracle/artifacts/REFERENCE_ORACLE_ONLY/`: config, completion, provenance, per_image.csv/json, independent_summary.json, independent_aggregation.json,100 per-image oracle_states.json files with both loss histories and best/final states.','- Original remote run contains100 float oracle_output.pt files; their byte hashes are in provenance. Full run plus source release is backed up on F disk; compact evidence is fetched into this project. See T025A_artifact_receipt.json for exact archive hashes.','','No changes to T022-C/T023-A, no baseline inference, no official test, and no further optimizer trial. Stop for research-lead review.','','oracle ceiling measured']
g=json.loads((r/'T025A_gate_groups.json').read_text())
extra=['## Descriptive frozen-gate groups','','These groups use the original low-only gate labels, not reference-derived relabeling. They describe heterogeneity and do not change any image or method.','','| Frozen active gate types | Images | Mean delta PSNR | Mean delta SSIM | Oracle mean PSNR | SSIM worse |','|---|---:|---:|---:|---:|---:|']
for name,a in g['groups'].items():
    extra.append(f"| {name} | {a['images']} | {a['delta_psnr_mean']:+.6f} | {a['delta_ssim_mean']:+.6f} | {a['oracle_psnr_mean']:.6f} | {a['ssim_worse']} |")
extra+=['',f"All {g['physical']['bright_ev']['count']} active bright-winner EV coordinates remain at their allowed upper bound 0. The {g['physical']['dark_ev']['count']} dark-winner EV coordinates have median {g['physical']['dark_ev']['median']:.9f}, near +2 but none meets the tight1e-6 upper-saturation tolerance. Therefore the aggregate EV-upper count86 refers to bright-winner zero bounds, not dark +2 endpoints. Gamma lower saturation is388/392 active coordinates.",'','This is evidence for both reachable improvement within the frozen family and strong boundary use; it does not by itself distinguish a certified action-family optimum from finite-search limitations.','']
position=lines.index('## Evidence locations');lines[position:position]=extra
(r/'T025A_oracle_ceiling.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print('Report generated from completed evidence')
