from pathlib import Path
import json,datetime
p=Path('research_log');r=p/'T045A_result';s=json.loads((r/'audit/summary.json').read_text());f=json.loads((r/'audit/freeze.json').read_text());e=json.loads((r/'audit/evaluation_receipt.json').read_text());replay=json.loads((r/'audit/independent_replay.json').read_text());auth=json.loads((r/'evaluation_deployment.json').read_text());export=json.loads((r/'audit/outputs/receipt.json').read_text());b=json.loads((p/'T045A_binding.json').read_text());arc=json.loads((p/'T045A_archives.json').read_text())
m=s['metrics'];lines=['# T045-A: SNR-Aware fixed-validation benchmark','',
f"**SNR-Aware development benchmark complete.** On the fixed 100-image development validation split, SNR-Aware mean PSNR is **{m['snr_psnr']['mean']:.10f} dB**, RGB-SSIM **{m['snr_ssim']['mean']:.10f}**. All provenance, output-freeze, target-isolation and independent-replay checks pass. There is no performance threshold.",'',
'**Training-exposed development anchor:** this split was carved from official LOL-v2 Real training pairs and the released SNR-Aware checkpoint is supervised on LOL-v2 Real. These numbers are not independent held-out SOTA evidence. Retinexformer below has the same training-exposure caveat.','',
'## Fixed bindings and inference','',
f"Split SHA `{f['split_sha256']}`, exactly the accepted T022/T033 100-image split. Canonical upstream `JIA-Lab-research/SNR-Aware-Low-Light-Enhance`, commit `{b['upstream_commit']}`. All53 accepted source-file hashes are pinned in `T027B_source_binding.json` and checked before and after inference; no upstream change. Checkpoint `LOLv2_real.pth`, **156523164 bytes**, SHA `432d29d370e9f674f1b6763d371b4c24569a86d21f0fd45a5797226274d85781`. Unchanged T027-B exporter SHA `{b['files']['ttie/snr_exporter.py']}`, unchanged config SHA `{b['files']['research_log/T027B_evidence/export_config.json']}`. T045 binding contains68 source/checkpoint/exporter/config/local-code hashes; it does not open any prior metric file during inference.",'',
'Mode is exactly `ttie_native_pad16`: native RGB float32/255, official5x5 low-derived blur, right/bottom reflect padding of low and blurred feature to a multiple of16, low-derived SNR, direct network, native unpad and clamp[0,1], HWC float32 output. The accepted exporter main is called unchanged. No resize-based test4, ensemble, GT statistics, brightness matching or alternative configuration.','',
f"Source **62de789443ff951123868697f43071559a3f0386**, branch `codex/T045A-snr-benchmark`, PR https://github.com/word-ky/TTIE/pull/70. Release `20260915-161131-ttie-t045a-snr`; GPU1 inference run `20260915-161153-ttie-t045a-snr`. Environment: `CUDA_VISIBLE_DEVICES=1`, `CUBLAS_WORKSPACE_CONFIG=:4096:8`, `PYTHONPATH=$PWD`, OMP/MKL/OPENBLAS threads1. Seed7 and deterministic cuDNN settings are the unchanged exporter settings. Exact command and environment in `T045A_result/inference/run.sh`. Local4tests passed13.87s; server4tests passed1.32s; wrapper/evaluator/replay compilation passed. Tests cover accepted padding/unpad parity, low-derived SNR normalization, low-only CLI and freeze authorization binding.",'',
'## Output freeze and evaluation boundary','',
f"Exactly100 low paths decoded, in the split order. cv2 image reads are limited to those100 paths and PIL decoding is disabled during inference. All input hashes, output count400x600x3 shape, float32 dtype, finiteness, [0,1] range, tensor-value hashes and output-file hashes pass. Parameter hash before/after is identical to accepted T027-B: `{export['parameter_hash_before']}`. Zero learned-parameter updates; no Ours/adaptation/selection changes.",'',
f"All100 outputs frozen **{f['completed_utc']}**, freeze SHA `{auth['freeze_sha256']}`. External evaluation authorization **{auth['created_utc']}**, strictly later. The freeze lists every input/output hash and decoded path; zero normal decodes before freeze. Evaluation run `20260915-161312-ttie-t045a-eval` opens only the same100 paired normals after the freeze and validates every normal hash and pairing. Both actual runs exit0. No official-test access, fresh cohort, retraining or reference-driven decision.",'',
'## Comparable development results','',
'| Method | Mean PSNR | Median PSNR | Mean RGB-SSIM | Median RGB-SSIM |','|---|---:|---:|---:|---:|',
f"| T026-A (accepted, not rerun) | {m['ours_psnr']['mean']:.7f} | {m['ours_psnr']['median']:.7f} | {m['ours_ssim']['mean']:.7f} | {m['ours_ssim']['median']:.7f} |",
'| T033 Retinexformer (accepted, not rerun) | 21.4787864 | 21.3989408 | 0.7900612 | 0.8160833 |',
f"| T045 SNR-Aware | {m['snr_psnr']['mean']:.7f} | {m['snr_psnr']['median']:.7f} | {m['snr_ssim']['mean']:.7f} | {m['snr_ssim']['median']:.7f} |",'',
f"Descriptive paired SNR-minus-T026 differences: PSNR mean **{m['delta_psnr']['mean']:+.10f} dB**, median **{m['delta_psnr']['median']:+.10f} dB**; RGB-SSIM mean **{m['delta_ssim']['mean']:+.10f}**, median **{m['delta_ssim']['median']:+.10f}**. Both metrics improve on99 images and decline on1 (these counts need not identify the same image). Exact accepted T026 CSV SHA `{b['ours_csv_sha256']}`; only read after the output freeze. No T026 or Retinexformer inference was rerun, and these comparisons create no gate.",'',
'## Metric convention and independent replay','',
'Reuse accepted T033/T026 pixels and RGB-SSIM: native400x600 RGB, no crop/resize/Y conversion/output quantization or brightness matching. Normal uint8/255 is rounded tofloat32 before promotion tofloat64; output float32 is promoted tofloat64. PSNR=-10log10(mean squared RGB error), range1. RGB-SSIM uses11x11 Gaussian sigma1.5, K1=.01/K2=.03, population covariance, reflect half-sample symmetric borders, all pixels/RGB channels averaged. The main evaluator changes only baseline names/labels from T033; metric math is unchanged.','',
f"Main per-image alternative calculation max error **{e['independent_metric_max_abs_error']:.16g} <1e-11**. In addition, a separate replay reloads all100 frozen outputs and100 normals, checks hashes again, recomputes200 PSNR/SSIM values with torch float64 PSNR and explicit separable convolve1d SSIM (main gaussian_filter), and recomputes means/medians with standard-library statistics without importing the main aggregation path. It also recomputes paired T026 deltas. **{replay['scalar_checks']} scalar checks**, max discrepancy **{replay['max_abs_error']:.16g} <=1e-10**, PASS; replay elapsed **{replay['seconds']:.6f}s**. All output hashes remain unchanged.",'',
'## Runtime, artifacts and failures','',
f"Exporter forward-only runtime: total **{sum(x['runtime_s'] for x in export['rows']):.9f}s**, mean **{s['runtime']['mean']:.9f}s/image**, median **{s['runtime']['median']:.9f}s/image**, p95 **{s['runtime']['p95']:.9f}s/image**. Peak allocated GPU memory **{s['peak_memory_bytes']} bytes**. These timings exclude model load, disk decode/write and evaluation; the first forward is included, so do not read them as end-to-end service latency.",'',
'No failures, retries or scientific deviations. The existing NVML initialization warning was nonblocking; CUDA inference completed and driver configuration was unchanged. One fixed SNR benchmark only; no search or model modification.','',
f"All100 output hashes and all68 source/checkpoint bindings were verified again during archival. Full inference+evaluation archive on F: **{arc['full']['bytes']} bytes**, SHA `{arc['full']['sha256']}`, path `{arc['full']['path']}`. Compact evidence **{arc['compact']['bytes']} bytes**, SHA `{arc['compact']['sha256']}`, verified at home/F shared/t045a and locally. Full float outputs remain on the server and F archive; compact provenance, per-image metrics, summaries, commands and logs are in this PR and project research_log. A Git-exact recovery bundle preserves final source/evidence and published main-mailbox entry.",'',
'Stop after this benchmark. The missing strong-baseline row is now available for the research lead to decide the next method investment. Do not infer independent held-out superiority, tune Ours, or launch another baseline from this task.','',
'SNR-Aware development benchmark complete']
(p/'T045A_report.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
d=dict(status='DONE',completed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),source='62de789443ff951123868697f43071559a3f0386',release='20260915-161131-ttie-t045a-snr',inference_run='20260915-161153-ttie-t045a-snr',evaluation_run='20260915-161312-ttie-t045a-eval',pr='https://github.com/word-ky/TTIE/pull/70',classification='SNR-Aware development benchmark complete',summary=s,independent_replay=replay,archives=arc,tests={'local':'4passed13.87s','server':'4passed1.32s','compile':'PASS'},failures=[],scientific_deviations=[],inference_attempts=1,evaluation_attempts=1,official_test_access=False,training_exposed=True,next_step='Stop after single benchmark; await research-lead review.')
d.update(main_mailbox_sha='bbe71daed742ccbce38a7f26ea174e0bf0f5e64d',main_mailbox_url='https://github.com/word-ky/TTIE/blob/bbe71daed742ccbce38a7f26ea174e0bf0f5e64d/coordination/CODEX_TO_CHATGPT.md',scientific_evidence_sha='d76c17b0439b46cf775e611fe86a7bdd30691a7a')
(p/'T045A_delivery.json').write_text(json.dumps(d,indent=2)+'\n')
