import sys,pathlib,json,hashlib,torch,numpy as np
from ttie.energy_model import load_energy
out=pathlib.Path(sys.argv[1]);r=json.loads((out/'result.json').read_text());sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();assert all(sha(p)==h for p,h in r['inputs_before'].items());assert r['inputs_before']==r['inputs_after'];assert all(sha(out/n)==h for n,h in r['marker']['files'].items());assert sha(out/'heldout_rows.pt')==r['held_rows_sha256'];torch.set_num_threads(1);head=load_energy(out/'head.pt');metrics={}
for side in ['train','heldout']:
 access=json.loads((out/(side+'_access.json')).read_text());features=[];mse=[]
 for name in access['bank_files']:
  if name.endswith('/bank.pt'):features.append(torch.load(name,weights_only=True,map_location='cpu')['features'])
  elif name.endswith('/targets.json'):mse.extend(v['mse'] for v in json.loads(pathlib.Path(name).read_text()))
 x=torch.cat(features);saved=torch.load(out/(side+'_rows.pt'),weights_only=True,map_location='cpu');a=saved['anchors'];p=head.standardized(x);t=((torch.tensor(mse,dtype=torch.float64)+1e-6).log().float()-head.y_mean)/head.y_scale;assert torch.equal(p,saved['p']) and torch.equal(t,saved['t']);dp=p-p[a];dt=t-t[a];assert torch.equal(dp,saved['delta_p']) and torch.equal(dt,saved['delta_t']);v=np.abs(dp.numpy()-dt.numpy());loss=np.where(v<1,np.float32(.5)*v*v,v-np.float32(.5));assert np.array_equal(loss,saved['loss'].numpy());h=float(torch.from_numpy(loss).mean());assert h==r[side]['huber'];metrics[side]=h
history=json.loads((out/'history.json').read_text());gen=torch.Generator().manual_seed(7)
for i,row in enumerate(history):
 order=torch.randperm(4357,generator=gen);assert hashlib.sha256(order.numpy().tobytes()).hexdigest()==row['order_sha256'] and row['epoch']==i+1
assert len(history)==100;opt=torch.load(out/'optimizer.pt',weights_only=True,map_location='cpu');assert {int(v['step']) for v in opt['state'].values()}=={1800};assert torch.equal(gen.get_state(),torch.load(out/'generator.pt',weights_only=True));assert r['marker']['persisted_utc']<r['held_opened_utc'];limit=.07650849781930447;label='scalar-only fixed recipe does not fit the inner-train scalar objective; stop as capacity/optimization inconclusive' if metrics['train']>limit else 'scalar-only transfer passes; joint Sobolev objective interference is supported as the cause of T059-E scalar failure' if metrics['heldout']<=limit else 'removing joint Sobolev losses does not rescue unseen-image scalar transfer; scalar conditioning/generalization remains unsupported under the current 28-D EnergyHead';assert label==r['classification'];assert r['counters']['training_runs']==1 and r['counters']['optimizer_steps']==1800;assert all(v==0 for k,v in r['counters'].items() if k not in ['training_runs','optimizer_steps']);z=dict(verification='PASS',frozen_checkpoint_replay_all_5886_predictions_targets_losses_exact=True,epoch100_batch_order_seed7_exact=True,optimizer_steps=1800,huber=metrics,classification=label,result_sha256=sha(out/'result.json'));(out/'verification.json').write_text(json.dumps(z,indent=2));print(json.dumps(z))
