from pathlib import Path
import json,datetime
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
p=Path('research_log');r=p/'T046A_result';s=json.loads((r/'audit/summary.json').read_text());f=json.loads((r/'audit/freeze.json').read_text());pre=json.loads((r/'preflight/preflight.json').read_text());replay=json.loads((r/'audit/independent_replay.json').read_text());receipt=json.loads((r/'audit/evaluation_receipt.json').read_text());pairs=json.loads((r/'audit/pairs.json').read_text());arc=json.loads((p/'T046A_archives.json').read_text());m=s['metrics'];active=json.loads((p/'T046A_active.json').read_text())
fig,axes=plt.subplots(1,2,figsize=(10,4))
for ax,key,label in zip(axes,['psnr','ssim'],['Paired PSNR change (dB)','Paired RGB-SSIM change']):
    y=sorted(v['delta_'+key] for v in pairs);ax.bar(range(100),y,width=1,color=['#278044' if v>=0 else '#c45325' for v in y]);ax.axhline(0,color='black',lw=.8);ax.set(xlabel='Pairs sorted by metric change',ylabel=label);ax.grid(axis='y',alpha=.15)
fig.suptitle('Fixed 1000-update extension minus accepted T035 oracle');fig.tight_layout()
for ext in ['png','pdf']:fig.savefig(r/f'paired_extension.{ext}',dpi=170)
lines=['# T046-A: common-gain oracle convergence extension','',f"**{s['classification']}**. Paired T046-minus-T035 PSNR mean **{m['delta_psnr']['mean']:+.10f} dB**, median **{m['delta_psnr']['median']:+.10f} dB**. The only gate is mean>=1.00 AND median>=0.75. SSIM, counts, endpoint frequency and baseline gaps are descriptive only.",'',
'**REFERENCE_ORACLE_ONLY.** Normals are permitted exclusively inside this isolated reachability/convergence diagnostic. No reference, oracle state or result enters deployable TTT, checkpoint selection or learned-energy training. Official LOL-v2 Real test remains untouched.','',
'## Exact input/source bindings and low-only preflight','',
f"Same frozen T022/T033100-image split SHA `{pre['split_sha256']}`. Accepted T035 output freeze SHA `{pre['prior_freeze_sha256']}`. The T035 renderer, hard Region2 masks/gate, EV/gamma bounds, RGB-shared gain bounds/order, native float32 decoding and optimizer function are reused unchanged. Complete original T035 source-binding checks pass, plus T046 source-binding SHA `{pre['source_binding_sha256']}`. The immutable accepted source tree and new orchestration are enumerated in T046A_source_binding.json.",'',
f"Before any normal decode, all100 accepted T035 winning states were verified against their original two-start histories, earliest winning step, gate/box and output files. All100 winners reconstructed from low image+fixed gate/raw state with **max absolute error {pre['all100_max_abs']}**, **all bit-exact={pre['all100_bit_exact']}**. Frozen starts SHA `{pre['starts_sha256']}`. Preflight complete **{pre['completed_utc']}**, SHA `{f['preflight_sha256']}`; exactly100 allowed low decodes, normal decodes0. This reads already-accepted reference-derived T035 winner metadata for identity verification; it does not recompute a winner from new reference information.",'',
'## Fixed optimization and selection','',
'Exactly100 images x one frozen T035 winning start x1000 Adam updates =100000 updates. Fresh Adam lr0.05 is constructed independently per image by the unchanged accepted optimize_start function; no prior moments existed to resume. This is a fixed restart-at-winner convergence probe, not a literal optimizer-moment continuation. Objective is full-frame RGB-MSE with float64 accumulation through the unchanged float32 renderer. Retain step0 and1000 updated states/MSEs; select earliest strict minimum. No alternate start, budget, optimizer, operator, bounds, geometry, full-WB run or scientific retry.','',
f"All100 selected outputs/states frozen **{f['completed_utc']}**, SHA `{receipt['freeze_sha256']}`, before the PSNR/SSIM evaluator. Every row binds the raw-state hash, selected-output tensor hash and output/history file hashes. All100100 retained states are finite and bounded; inactive gain coordinates remain identity. Normals opened only after the common preflight, validated by exact image pairing and hash.",'',
'## Results','',
'| State | Mean PSNR | Median PSNR | Mean RGB-SSIM | Median RGB-SSIM |','|---|---:|---:|---:|---:|',
f"| Accepted T035 | {m['t035_psnr']['mean']:.10f} | {m['t035_psnr']['median']:.10f} | {m['t035_ssim']['mean']:.10f} | {m['t035_ssim']['median']:.10f} |",
f"| T046 fixed extension | {m['psnr']['mean']:.10f} | {m['psnr']['median']:.10f} | {m['ssim']['mean']:.10f} | {m['ssim']['median']:.10f} |",
f"| Paired difference | {m['delta_psnr']['mean']:+.10f} | {m['delta_psnr']['median']:+.10f} | {m['delta_ssim']['mean']:+.10f} | {m['delta_ssim']['median']:+.10f} |",'',
f"PSNR win/equal/loss: **{s['win_equal_loss']['psnr']}**. SSIM: **{s['win_equal_loss']['ssim']}**. Best extension step1000 on **{s['at_step1000']}/100** images. Full earliest-best-step histogram: `{json.dumps(s['best_step_histogram'],sort_keys=True)}`.",'',
'![Paired extension changes](T046A_result/paired_extension.png)','',
f"Remaining mean gaps (anchor minus T046): T033 Retinexformer **{21.4787864-m['psnr']['mean']:+.7f} dB / {0.7900612-m['ssim']['mean']:+.7f} SSIM**; T045 SNR-Aware **{23.39632992074517-m['psnr']['mean']:+.7f} dB / {0.8237643949325277-m['ssim']['mean']:+.7f} SSIM**. Only prior scalar anchors are used; no anchor output was loaded by optimization or selection. These supervised baselines are training-exposed development anchors, not independent held-out SOTA comparisons. The present oracle is non-deployable.",'',
'## Metric and independent replay','',
'Exact accepted T035/T026 native RGB pixel handling: float32 pixels promoted tofloat64, no crop/resize/Y conversion/brightness matching. PSNR is full RGB-MSE; RGB-SSIM range1,11x11 Gaussian sigma1.5, K1=.01/K2=.03, population covariance, reflect half-sample symmetric borders retained. T035 paired CSV is immutable, SHA `d531c45ce670f5b84c2b74059e931350e21e49c7d1c70d15229f4fbb26a24d72`.','',
f"Independent replay imports no main T046 score/statistics/verdict helper. It reads all100 histories, independently selects the earliest minimum, checks exact raw/start/output hashes, validates100100 finite bounded states using NumPy physical maps, recomputes200 selected-image PSNR/SSIM values with torch float64 MSE and explicit separable convolve1d SSIM, then reconstructs paired deltas/means/medians/counts/full best-step histogram/verdict. **{replay['scalar_checks']} scalar checks**, max discrepancy **{replay['max_abs_error']:.16g} <=1e-10**, PASS; elapsed **{replay['seconds']:.6f}s**. Preflight-before-normal and freeze-before-metric ordering are independently checked.",'',
'## Execution, failures and recovery','',
f"Tested source **4ecababa94fb6779537cdebad1ee13bc0f734124**, branch `codex/T046A-oracle-convergence`, PR https://github.com/word-ky/TTIE/pull/71. Release `20260915-173225-ttie-t046a-extension`; GPU1 preflight `20260915-173248-ttie-t046a-preflight`; GPU1 oracle `20260915-173335-ttie-t046a-oracle`; evaluation `{active['evaluation_run']}`. Exact commands in saved run.sh files. CUDA_VISIBLE_DEVICES1, CUBLAS_WORKSPACE_CONFIG=:4096:8, seed7, TF32off, OMP/MKL/OPENBLASthreads1. Preflight **{pre['seconds']:.6f}s**; oracle100-image wall-time sum **{s['runtime_seconds']:.6f}s**. Allactual runs exit0.",'',
'Validation: accepted baseline2tests24.13s; focused2tests21.67s; server4tests2.55s; allpass. Focused checks verify original optimizer identity, fresh-moment repeated-start behavior, retained states/earliest minima and both verdict boundaries.','',
'One infrastructure failure: SSH255 connection closed during initial oracle launch before tmux started. Confirmed no session and no log, then launched the exact already-generated run.sh once. No partial trajectory, repeated image, altered settings or scientific restart. Existing NVML/protobuf deprecation warnings were nonblocking. Report-generator quoting errors were caught by compilation and corrected before result generation. No scientific deviation, deployable modification, model training, official-test access or extra probe.','',
f"All selected-output/history and source hashes reverified during archival. Full F archive **{arc['full']['bytes']} bytes**, SHA `{arc['full']['sha256']}`. Compact evidence including all retained raw/MSE histories **{arc['compact']['bytes']} bytes**, SHA `{arc['compact']['sha256']}`, verified home/F/local. Raw output images remain server/F; compact histories, starts, receipts, metrics, reports and Git-exact recovery are retained in project research_log. Main Codex mailbox receives one append-only completion report.",'',
'Stop after this one fixed convergence probe. Interpret the verdict as evidence about this specified budget and fresh-Adam probe; do not infer a global optimum or a hard capacity ceiling, and do not launch another operator/retraining experiment without the next research task.','',s['classification']]
(p/'T046A_report.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
delivery=dict(status='DONE',completed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),tested_source='4ecababa94fb6779537cdebad1ee13bc0f734124',pr='https://github.com/word-ky/TTIE/pull/71',summary=s,replay=replay,archives=arc,runs={k:active[k] for k in ['preflight_run','oracle_run','evaluation_run']},tests={'baseline':'2passed24.13s','focused':'2passed21.67s','server':'4passed2.55s'},failures=['SSH255 before oracle process launch; resumed exact generated script once','Report-generator quoting errors corrected before result generation'],scientific_deviations=[],label='REFERENCE_ORACLE_ONLY',official_test_access=False,next_step='Stop after fixed probe; await research-lead review.')
previous=p/'T046A_delivery.json'
if previous.exists():
    old=json.loads(previous.read_text())
    for key in ['main_mailbox_sha','main_mailbox_url','scientific_evidence_sha']:
        if key in old:delivery[key]=old[key]
previous.write_text(json.dumps(delivery,indent=2)+'\n')
