import argparse
from ttie.natural import load_image
from research_log.T060A.core import *
p=argparse.ArgumentParser();p.add_argument('--out',type=Path,required=True);out=p.parse_args().out;torch.set_num_threads(1);f=json.loads((out/'prediction_freeze.json').read_bytes());assert f['rows']==80;validate({str(out/n):h for n,h in f['files'].items()});validate(f['inputs']);validate(f['source_bindings'])
first=utc();assert first>f['utc'];atomic_json(out/'reference_open.json',dict(first_source_clean_read_utc=first,prediction_freeze_utc=f['utc']));manifest=Path('research_log/T014_source_manifest.json');assert sha(manifest)=='4dbf8c604bc44574a5823ec8e22142c8ac39574b6103c4bbd0a69647f15a2257';sources={r['image_id']:r for r in json.loads(manifest.read_bytes())['images'] if r['split']=='train_t014_sobolev'};clean={};opens=[];rows=[];grads={}
for r in json.loads((out/'predictions.json').read_bytes()):
    i=r['image_id']
    if i not in clean:
        s=sources[i];path=ROOT/'shared/t008/val2017'/s['filename'];assert sha(path)==s['sha256'];clean[i]=load_image(path).cuda();opens.append(dict(image_id=i,path=str(path),sha256=s['sha256'],utc=utc()))
    t=torch.load(out/r['file'],weights_only=True,map_location='cpu');model=Exposure(t['base'].cuda(),t['grid'].cuda());assert model.base.shape==clean[i].shape;loss=(model().double()-clean[i].double()).square().mean();gR,=torch.autograd.grad(loss,model.u);assert torch.isfinite(gR).all() and torch.count_nonzero(model.u)==0;g=t['g'].double().flatten();ref=gR.detach().cpu().double().flatten();an=float(g.norm());bn=float(ref.norm());dot=float(torch.dot(g,ref));cos=dot/(an*bn) if an*bn else 0.;rows.append(dict(index=r['index'],image_id=i,bank_index=r['bank_index'],predicted_norm=an,reference_norm=bn,dot=dot,cosine=cos,positive_dot=dot>0,nondegenerate=an>1e-12 and bn>1e-12));grads[r['bank_index']]=gR.detach().cpu()
assert len(clean)==16 and len(rows)==80;save_tensor(out/'reference_gradients.pt',grads);atomic_json(out/'source_clean_reads.json',opens);atomic_json(out/'alignment_table.json',rows);validate({str(out/n):h for n,h in f['files'].items()});validate(f['inputs']);atomic_json(out/'result.json',dict(**summaries(rows),prediction_freeze_utc=f['utc'],first_source_clean_read_utc=first,optimizer_steps=0,target_domain_access=0,lolv2_access=0,official_test_access=0,inference_reference_leakage=0,completed_utc=utc()));print(json.dumps(summaries(rows)),flush=True)
