import argparse
from ttie.clip_signal import FrozenCLIP
from ttie.learned_prototypes import Prototypes
from ttie.semantic_ttt import SemanticScorer
from ttie.common_gain import CommonRegion2
from ttie.energy_model import load_energy,features
from research_log.T059A.support import detail_jacobian
from research_log.T060A.core import *
p=argparse.ArgumentParser();p.add_argument('--out',type=Path,required=True);out=p.parse_args().out;out.mkdir(parents=True,exist_ok=False);start=utc();torch.set_num_threads(1);torch.manual_seed(7);torch.backends.cuda.matmul.allow_tf32=False;torch.backends.cudnn.allow_tf32=False
binding=json.loads(Path('research_log/T060A/source_binding.json').read_bytes());cohort=json.loads(Path('research_log/T060A/cohort.json').read_bytes());inputs=cohort['inputs'];firewall(set(inputs)|{str(Path(n).resolve()) for n in binding}|{str(Path('research_log/T060A/source_binding.json').resolve())},out);validate(binding);validate(inputs)
sf=json.loads(Path('research_log/T060A/cohort_freeze.json').read_bytes());assert sha('research_log/T060A/cohort.json')==sf['sha256'] and sf['utc']<start
config=json.loads((B/'config.json').read_bytes());encoder=FrozenCLIP.from_checkpoint(config['model_identity']['path'],'cuda:0');proto=ROOT/'research_log/remote_runs/20260912-071126-ttie-t006-a6000/artifacts/audit/prototypes.pt';scorer=SemanticScorer(encoder,Prototypes(torch.load(proto,weights_only=True,map_location='cuda:0')['raw'])).eval().requires_grad_(False);head=load_energy(E/'head.pt').eval().requires_grad_(False);before={k:thash(t) for k,t in head.state_dict().items()};records=[]
for r in cohort['anchors']:
    directory=Path(r['directory']);bank=torch.load(directory/'bank.pt',weights_only=True,map_location='cpu');low=torch.load(directory/'bank_images.pt',weights_only=True,map_location='cpu')[0].cuda();gate=r['gate'];active=torch.tensor(gate['active'],device='cuda:0',dtype=torch.bool);obj=SimpleNamespace(active=active,winner=torch.tensor(gate['winner'],device='cuda:0'),evidence=torch.tensor(gate['evidence'],device='cuda:0',dtype=torch.float64),calibration=cohort['calibration']);legacy=CommonRegion2(active).cuda().requires_grad_(False);raw=probe_raw(bank['states'][0],active.cpu(),1.)
    with torch.no_grad():legacy.raw.copy_(raw.cuda());y0=legacy(low);grid=legacy.physical_grid()[:,:2]
    assert thash(y0)==r['state_before']['y0'] and thash(grid)==r['state_before']['grid'];model=Exposure(y0,grid);x=features(obj,scorer(model()),model.grid);J=detail_jacobian(x,model.u).detach().cpu();leaf=x.detach().cpu().float().requires_grad_(True);q,=torch.autograd.grad(head(leaf).sum(),leaf);g=torch.einsum('fi,f->i',J,q).detach();assert torch.count_nonzero(model.u)==0
    tensors=dict(x=x.detach().cpu(),J=J,q=q.detach(),g=g,base=y0.cpu(),grid=grid.cpu(),raw=raw,u=model.u.detach().cpu());assert all(torch.isfinite(t).all() for t in tensors.values());name=f"prediction_{r['bank_index']:03d}.pt";save_tensor(out/name,tensors);records.append(dict(**r,file=name,sha256=sha(out/name),tensor_hashes={k:thash(t) for k,t in tensors.items()},norm=float(g.double().norm()),persisted_utc=utc()));print(json.dumps(dict(completed=len(records),bank=r['bank_index'])),flush=True)
assert len(records)==80 and before=={k:thash(t) for k,t in head.state_dict().items()};validate(binding);validate(inputs);atomic_json(out/'predictions.json',records);atomic_json(out/'prediction_freeze.json',dict(utc=utc(),started_utc=start,rows=80,files={n:sha(out/n) for n in ['predictions.json']+[r['file'] for r in records]},inputs=inputs,source_bindings=binding,head_state_before=before,head_state_after=before,normalization=head.normalization(),optimizer_steps=0,clean_reference_reads=0,reference_gradient_reads=0,target_domain_access=0,lolv2_access=0,official_test_access=0,inference_reference_leakage=0,physical_gpu=1));print('ALL80_TARGET_FREE_FROZEN',flush=True)
