import pathlib,sys,json,hashlib,numpy as np,torch
from research_log.T059I.core import tensor_only
out=pathlib.Path(sys.argv[1]);r=json.loads((out/'result.json').read_text());mark=r['marker'];sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();assert all(sha(n)==h for n,h in r['inputs_before'].items());assert r['inputs_before']==r['inputs_after'];assert sha(out/'maps.pt')==mark['maps_sha256'] and sha(out/'anchors_dx.pt')==mark['anchors_sha256'];assert sha(out/'evaluation_rows.pt')==r['evaluation_rows_sha256']
gpath=next(n for n in r['inputs_before'] if n.endswith('/T059G/maps.pt'));sp=next(n for n in r['inputs_before'] if n.endswith('/split.json'));scalar=next(n for n in r['inputs_before'] if n.endswith('/T059G/evaluation_rows.pt'));g=torch.load(gpath,weights_only=True,map_location='cpu');split=json.loads(pathlib.Path(sp).read_text());a=torch.load(out/'anchors_dx.pt',weights_only=True,map_location='cpu');nn=torch.load(out/'maps.pt',weights_only=True,map_location='cpu');rows=torch.load(out/'evaluation_rows.pt',weights_only=True,map_location='cpu');dx={};targets={};metrics={};errors={}
for s in ['train','heldout']:
 ids=split['row_indices'][s];records=[split['canonical'][i] for i in ids];bank=np.array([v['bank_index'] for v in records]);state=np.array([v['state_index'] for v in records]);anchor=np.empty(len(ids),dtype=np.int64)
 for b in np.unique(bank):
  z=np.flatnonzero((bank==b)&(state==0));assert len(z)==1;anchor[bank==b]=z[0]
 assert np.array_equal(anchor,a[s]['anchor'].numpy());assert np.array_equal(np.array(ids)[anchor],a[s]['anchor_global'].numpy());dx[s]=g[s]['x'].numpy()-g[s]['x'].numpy()[anchor];assert np.array_equal(dx[s],a[s]['dx'].numpy());targets[s],_=tensor_only(scalar,s,'target')
tr=dx['train'].astype(np.float64);images=g['train']['image'].numpy();globals=g['train']['global_index'].numpy();assert np.all(globals[:-1]<globals[1:])
for s in ['train','heldout']:
 q=dx[s].astype(np.float64);err=0
 for start in range(0,len(q),32):
  d=np.square(q[start:start+32,None,:]-tr[None,:,:]).sum(-1);allowed=(g[s]['image'][start:start+32].numpy()[:,None]!=images[None,:]) if s=='train' else np.ones(d.shape,dtype=bool);d[~allowed]=np.inf;idx=d.argmin(1);v=d[np.arange(len(idx)),idx];sl=slice(start,start+len(idx));assert np.array_equal(idx,nn[s]['index'][sl].numpy());assert np.array_equal((d==v[:,None]).sum(1),nn[s]['tie_count'][sl].numpy());assert np.array_equal(allowed.sum(1),nn[s]['candidate_count'][sl].numpy());saved=nn[s]['distance'][sl].numpy();assert np.allclose(v,saved,rtol=1e-12,atol=1e-12);err=max(err,float(np.abs(v-saved).max()))
 pred=targets['train'][nn[s]['index']];assert torch.equal(pred,rows[s]['pred']) and torch.equal(targets[s],rows[s]['target']);v=np.abs(pred.numpy()-targets[s].numpy());loss=np.where(v<1,np.float32(.5)*v*v,v-np.float32(.5));assert np.array_equal(loss,rows[s]['loss'].numpy());h=float(rows[s]['loss'].mean());assert h==r['statistics'][s]['huber'];metrics[s]=h;errors[s]=err;assert not (g[s]['image']==g['train']['image'][nn[s]['index']]).any()
limit=.07650849781930447;classification='bank-relative feature displacement is not even source-LOO consistent under fixed 1-NN; stop' if metrics['train']>limit else 'bank-relative feature displacement restores image-held scalar localization under fixed 1-NN; relative conditioning is supported as a mechanism' if metrics['heldout']<=limit else 'bank-relative feature displacement preserves train-LOO consistency but does not resolve unseen-image scalar localization';assert classification==r['classification'];assert mark['anchors_persisted_utc']<=mark['persisted_utc']<r['scalar_opened_utc'];assert all(v==0 for v in r['counters'].values());z=dict(verification='PASS',all_5886_anchors_dx_neighbors_predictions_losses_ties_verified=True,classification=classification,huber=metrics,max_distance_error=errors,result_sha256=sha(out/'result.json'));(out/'verification.json').write_text(json.dumps(z,indent=2));print(json.dumps(z))
