import pathlib,json,hashlib,datetime,os,argparse,torch
from research_log.T059R.storage import tensor_only
from research_log.T059R.core import descriptors,auroc,group_summary,spearman,classify
ROOT=pathlib.Path('/home/wenchang/asdasdsad/wjq/TTIE');Q=ROOT/'runs/20260918-183520-ttie-t059q-report-recovery/artifacts/T059Q';E=ROOT/'runs/20260918-023558-ttie-t059e-relative/artifacts/T059E';M=ROOT/'runs/20260918-123128-ttie-t059m-scalar/artifacts/T059M';HERE=pathlib.Path('research_log/T059R')
def sha(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def utc():return datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,v):
 with p.open('w') as f:json.dump(v,f,indent=2);f.flush();os.fsync(f.fileno())
def setup():
 torch.set_num_threads(1);inputs=json.loads((HERE/'inputs.json').read_text());own=json.loads((HERE/'source_binding.json').read_text());assert all(sha(p)==h for p,h in {**inputs,**own}.items());return inputs,own

def describe(out):
 inputs,own=setup();out.mkdir(parents=True,exist_ok=False);rows=json.loads((Q/'prediction_rows.json').read_text());qm=json.loads((Q/'decisions_persisted.json').read_text());assert sha(Q/'prediction_rows.json')==qm['predictions_sha256'];split=json.loads((E/'split.json').read_text());assert rows['global']==split['row_indices']['heldout'];rec=[split['canonical'][i] for i in rows['global']];assert all(rows[k]==[r[f] for r in rec] for k,f in [('bank','bank_index'),('state','state_index'),('image','image_id')]);assert len(rec)==1529 and len(set(rows['bank']))==80 and len(set(rows['image']))==16;access=[]
 for h,path in [('E',E/'heldout_row_values.pt'),('M',M/'heldout_rows.pt')]:
  t,a=tensor_only(path,'p');access.append(a);assert rows[h]==t.tolist()
 ma=json.loads((M/'heldout_access.json').read_text());er=json.loads((E/'heldout_receipt.json').read_text());mn=json.loads((M/'initial_final_hashes.json').read_text());assert ma['global_indices']==rows['global'];assert er['normalization']==mn['normalization']==qm['normalization'];ea,a=tensor_only(E/'heldout_row_values.pt','anchor_indices');access.append(a);mm,a=tensor_only(M/'heldout_rows.pt','anchors');access.append(a);assert torch.equal(ea,mm)
 for b in set(rows['bank']):
  ids=[i for i,k in enumerate(rows['bank']) if k==b];anchors=[i for i in ids if rows['state'][i]==0];assert len(anchors)==1 and all(int(ea[i])==anchors[0] for i in ids)
 try:table=descriptors(rows)
 except ValueError as error:
  write(out/'result.json',dict(status='BLOCKED',classification='T059-R blocked; no scientific classification',reason='T059-R blocked; fixed statistic undefined',detail=str(error),inputs=inputs,source_target_reads=0));raise SystemExit(2)
 assert len(table)==63;write(out/'prediction_rows.json',rows);write(out/'descriptors.json',table);write(out/'descriptors_persisted.json',dict(persisted_utc=utc(),descriptors_sha256=sha(out/'descriptors.json'),prediction_rows_sha256=sha(out/'prediction_rows.json'),inputs=inputs,source_binding=own,normalization=qm['normalization'],sources=qm['sources'],alignment=qm['alignment'],prediction_storage_reads=access,source_target_reads=0,non_singleton_banks=63,singletons_excluded=17,percentile_definition='100*(one_based_rank-1)/(N-1), from most uncertain; <=25 top quartile, <=10 top decile',uncertainty_ties='smallest bank ID',score_ties='average ranks',argmin_ties='smallest state_index then global row ID'));print('DESCRIPTORS_FROZEN',utc(),flush=True)

def evaluate(out):
 inputs,own=setup();mark=json.loads((out/'descriptors_persisted.json').read_text());assert sha(out/'descriptors.json')==mark['descriptors_sha256'] and sha(out/'prediction_rows.json')==mark['prediction_rows_sha256'];table=json.loads((out/'descriptors.json').read_text());opened=utc();assert mark['persisted_utc']<opened;t,access=tensor_only(E/'heldout_row_values.pt','delta_t');er=json.loads((E/'heldout_receipt.json').read_text());assert hashlib.sha256(t.numpy().tobytes()).hexdigest()==er['row_tensor_hashes']['delta_t'];assert sha(Q/'result.json')=='e4f34e27a982cb73507442b0964cfa3c1422b4baff101b967f63b5d63843b6ea';qr=json.loads((Q/'result.json').read_text());assert sha(Q/'evaluation_table.json')==qr['evaluation_table_sha256'];prior={b['bank']:b for b in json.loads((Q/'evaluation_table.json').read_text())}
 for b in table:
  harm=float(t[b['a_E']]-t[b['anchor']]);assert harm==prior[b['bank']]['policies']['E']['harm_vs_anchor'] and b['E_state']==prior[b['bank']]['E_state'];b.update(harm_vs_anchor=harm,unsafe_E=harm>0,positive_harm=max(harm,0.))
 assert all(b['policies']['E']['harm_vs_anchor']==0 for b in prior.values() if b['singleton']);unsafe=[b for b in table if b['unsafe_E']];auc=auroc([b['u'] for b in table],[b['unsafe_E'] for b in table]);corr=spearman([b['u'] for b in table],[b['positive_harm'] for b in table]);label,conditions=classify(table,auc);worst=max(table,key=lambda b:(b['harm_vs_anchor'],-b['bank']));write(out/'target_rows.json',dict(global_indices=json.loads((out/'prediction_rows.json').read_text())['global'],delta_t=t.tolist(),opened_utc=opened,storage=access));write(out/'evaluation_table.json',table);before={**inputs,str(Q/'result.json'):sha(Q/'result.json'),str(Q/'evaluation_table.json'):sha(Q/'evaluation_table.json')};after={p:sha(p) for p in before};assert before==after and all(sha(p)==h for p,h in own.items()) and sha(out/'descriptors.json')==mark['descriptors_sha256'];result=dict(task='T059-R',status='DONE',classification=label,conditions=conditions,unsafe_count=len(unsafe),non_singleton_count=len(table),auroc=auc,unsafe_banks=[{k:b[k] for k in ['bank','image','u','rho_EM','uncertainty_rank','uncertainty_percentile','harm_vs_anchor']} for b in unsafe],maximum_harm_bank={k:worst[k] for k in ['bank','u','uncertainty_rank','uncertainty_percentile','harm_vs_anchor']},groups={s:group_summary([b['u'] for b in table if b['unsafe_E']==flag]) for s,flag in [('unsafe',True),('safe',False)]},spearman_u_positive_harm=corr,marker=mark,target_opened_utc=opened,target_rows_sha256=sha(out/'target_rows.json'),evaluation_table_sha256=sha(out/'evaluation_table.json'),Q_E_harm_exact_all80=True,inputs_before=before,inputs_after=after,source=json.loads((HERE/'publication.json').read_text())['source'],authorization='c855b29275a203b6de2c110c5d576ca038db0a7c',counters={k:0 for k in ['training_runs','optimizer_steps','model_forwards','new_feature_forwards','source_target_reads_before_descriptor_freeze','outer_supervision_reads','target_domain_access','lolv2_access','official_test_access','inference_reference_leakage']},completed_utc=utc());write(out/'result.json',result);print(json.dumps({k:result[k] for k in ['classification','auroc','unsafe_banks','maximum_harm_bank','groups','spearman_u_positive_harm','conditions']}),flush=True)
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('stage',choices=['describe','evaluate']);p.add_argument('--out',type=pathlib.Path,required=True);a=p.parse_args();dict(describe=describe,evaluate=evaluate)[a.stage](a.out)
