import pathlib,sys,json,hashlib,torch,numpy as np
from research_log.T059I.core import tensor_only
out=pathlib.Path(sys.argv[1]);r=json.loads((out/'result.json').read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();torch.set_num_threads(1)
for n,h in r['inputs_before'].items():assert sha(pathlib.Path(n))==h==r['inputs_after'][n]
assert sha(out/'donor_values.pt')==r['donor_marker']['sha256'] and sha(out/'oracle_rows.pt')==r['oracle_rows_sha256'];table=torch.load(out/'donor_values.pt',map_location='cpu',weights_only=True);rows=torch.load(out/'oracle_rows.pt',map_location='cpu',weights_only=True)
G=pathlib.Path('/home/wenchang/asdasdsad/wjq/TTIE/runs/20260918-050302-ttie-t059g-nn/artifacts/T059G');I=pathlib.Path('/home/wenchang/asdasdsad/wjq/TTIE/runs/20260918-073334-ttie-t059i-five/artifacts/T059I');maps=torch.load(I/'maps.pt',map_location='cpu',weights_only=True);train,_=tensor_only(G/'evaluation_rows.pt','train','target');metrics={}
for s in ['train','heldout']:
 t,_=tensor_only(G/'evaluation_rows.pt',s,'target');assert torch.equal(table[s],train[maps[s]['index']]);v=table[s].numpy();err=np.abs(v-t.numpy()[:,None]);loss=np.where(err<1,np.float32(.5)*err*err,err-np.float32(.5));rank=loss.argmin(1);best=loss[np.arange(len(rank)),rank];assert np.array_equal(rank+1,rows[s]['best_rank'].numpy()) and np.array_equal(best,rows[s]['best_loss'].numpy());h=float(torch.from_numpy(best).mean());assert h==r['statistics'][s]['oracle_floor_huber'];metrics[s]=h
 assert np.bincount(rank,minlength=5).tolist()==r['statistics'][s]['rank_histogram'];assert float((rank==0).mean())==r['statistics'][s]['rank1_fraction'];ordered=np.sort(v,axis=1);assert float(((t.numpy()>=ordered[:,0])&(t.numpy()<=ordered[:,-1])).mean())==r['statistics'][s]['target_in_donor_range_fraction']
 for name,values in [('donor_range_distribution',ordered[:,-1]-ordered[:,0]),('donor_iqr_distribution',ordered[:,3]-ordered[:,1])]:
  x=values.astype('float64');expected=dict(rows=len(x),minimum=float(x.min()),mean=float(x.mean()),p10=float(np.quantile(x,.1)),median=float(np.quantile(x,.5)),p90=float(np.quantile(x,.9)),maximum=float(x.max()))
  assert all(np.isclose(value,r['statistics'][s][name][k],rtol=1e-12,atol=1e-12) for k,value in expected.items())
limit=.07650849781930447;classification='five-donor local scalar support is inadequate even on inner-train LOO under the frozen neighborhood' if metrics['train']>limit else 'accurate scalar support exists inside the frozen five-donor neighborhood; donor selection/conditioning, not local support absence, is the primary unresolved failure' if metrics['heldout']<=limit else 'even oracle choice among the frozen five donors cannot recover held scalar geometry; local 28-D scalar support is inadequate on inner-held images';assert classification==r['classification'];assert r['donor_marker']['persisted_utc']<r['held_scalar_opened_utc'];assert all(v==0 for v in r['counters'].values())
z=dict(verification='PASS',label='REFERENCE_ORACLE_ONLY',independent_classification=classification,oracle_floor_huber=metrics,all_5886_oracle_ranks_losses_exact=True,all_29430_frozen_donor_values_exact=True,range_IQR_coverage_verified=True,result_sha256=sha(out/'result.json'));(out/'verification.json').write_text(json.dumps(z,indent=2));print(json.dumps(z))
