import pathlib,sys,json,hashlib,torch,numpy as np
from ttie.energy_model import load_energy
out=pathlib.Path(sys.argv[1]);r=json.loads((out/'result.json').read_text());sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();torch.set_num_threads(1);assert all(sha(n)==v for n,v in r['inputs_before'].items());assert r['inputs_before']==r['inputs_after'];assert all(sha(out/n)==v for n,v in r['marker']['files'].items());assert sha(out/'selector_rows.pt')==r['selector_rows_sha256'];parent=json.loads(pathlib.Path(next(n for n in r['inputs_before'] if n.endswith('/T059E/split.json'))).read_text());ordered=sorted(parent['image_ids']['train'],key=lambda i:parent['group_indices'][str(i)]);selector=ordered[5::6];fit=[v for v in ordered if v not in selector];s=r['split'];assert s['sorted_parent_image_ids']==ordered and s['image_ids']==dict(fit=fit,selector=selector);assert len(fit)==40 and len(selector)==8 and not set(fit)&set(selector);data={}
for side in ['fit','selector']:
 expected=[i for i in parent['row_indices']['train'] if parent['canonical'][i]['image_id'] in s['image_ids'][side]];assert expected==s['row_indices'][side];assert not set(expected)&set(parent['row_indices']['heldout']+parent['row_indices']['outer']);access=json.loads((out/(side+'_access.json')).read_text());assert access['global_indices']==expected;xs=[];ms=[]
 for name in access['bank_files']:
  if name.endswith('/bank.pt'):xs.append(torch.load(name,weights_only=True,map_location='cpu')['features'])
  elif name.endswith('/targets.json'):ms.extend(v['mse'] for v in json.loads(pathlib.Path(name).read_text()))
 x=torch.cat(xs);mse=torch.tensor(ms,dtype=torch.float64);records=[parent['canonical'][i] for i in expected];bank=np.array([v['bank_index'] for v in records]);state=np.array([v['state_index'] for v in records]);a=np.empty(len(expected),dtype=np.int64)
 for b in np.unique(bank):
  z=np.flatnonzero((bank==b)&(state==0));assert len(z)==1;a[bank==b]=z[0]
 data[side]=(x,mse,torch.from_numpy(a),torch.load(out/(side+'_rows.pt'),weights_only=True,map_location='cpu'))
x,mse,_,_=data['fit'];log=(mse+1e-6).log();xs=x.double().std(0,unbiased=False);ys=log.std(unbiased=False);norm=dict(x_mean=x.double().mean(0).float(),x_scale=torch.where(xs==0,torch.ones_like(xs),xs).float(),y_mean=log.mean().float(),y_scale=torch.where(ys==0,torch.ones_like(ys),ys).float());curves={s:[] for s in data}
for epoch in range(1,101):
 head=load_energy(out/'checkpoints'/('epoch_%03d.pt'%epoch));assert all(torch.equal(getattr(head,k),v) for k,v in norm.items())
 for side,(x,mse,a,saved) in data.items():
  p=head.standardized(x);t=((mse+1e-6).log().float()-head.y_mean)/head.y_scale;dp=p-p[a];dt=t-t[a]
  for k,v in [('p',p),('t',t),('delta_p',dp),('delta_t',dt)]:assert torch.equal(v,saved[k][epoch-1])
  z=np.abs(dp.numpy()-dt.numpy());loss=np.where(z<1,np.float32(.5)*z*z,z-np.float32(.5));assert np.array_equal(loss,saved['loss'][epoch-1].numpy());curves[side].append(float(torch.from_numpy(loss).mean()))
assert curves['fit']==r['fit_curve'] and curves['selector']==r['selector_curve'];history=json.loads((out/'history.json').read_text());gen=torch.Generator().manual_seed(7)
for i,row in enumerate(history):
 order=torch.randperm(len(data['fit'][0]),generator=gen);assert hashlib.sha256(order.numpy().tobytes()).hexdigest()==row['order_sha256'];assert row['fit_huber']==curves['fit'][i]
assert len(history)==100 and torch.equal(gen.get_state(),torch.load(out/'generator.pt',weights_only=True));opt=torch.load(out/'optimizer.pt',weights_only=True,map_location='cpu');steps=100*((len(data['fit'][0])+255)//256);assert {int(v['step']) for v in opt['state'].values()}=={steps};eligible=[i+1 for i,v in enumerate(curves['fit']) if v<=.07650849781930447];chosen=min(eligible,key=lambda e:(curves['selector'][e-1],e)) if eligible else None;assert eligible==r['eligible_epochs'] and chosen==r['selected_epoch'];labels=['scalar-only fit does not reach the scalar gate on the 40-image nested fit; stop as optimization/capacity inconclusive','fixed source-only early stopping does not establish image-held scalar transfer under the current 28-D EnergyHead','nested source-only checkpoint selection passes the scalar gate; early-stopping regularization is supported as a viable source-validation mechanism'];label=labels[0] if chosen is None else labels[1] if curves['selector'][chosen-1]>.07650849781930447 else labels[2];assert label==r['classification'];assert r['marker']['persisted_utc']<r['selector_opened_utc'];assert all(v==0 for k,v in r['counters'].items() if k not in ['training_runs','optimizer_steps']);assert r['counters']['training_runs']==1 and r['counters']['optimizer_steps']==steps;z=dict(verification='PASS',all100_checkpoints_predictions_losses_split_normalization_selection_replayed=True,epoch_order_hashes_exact=True,selected_epoch=chosen,eligible_epochs=eligible,classification=label,optimizer_steps=steps,result_sha256=sha(out/'result.json'));(out/'verification.json').write_text(json.dumps(z,indent=2));print(json.dumps(z))
