import json,pathlib,datetime
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
log=pathlib.Path(__file__).resolve().parents[1];result=log/'T053A_result';audit=result/'audit'
def read(p):return json.loads(p.read_bytes())
s=read(audit/'summary.json');replay=read(audit/'independent_replay.json');pre=read(result/'preflight/preflight.json');freeze=read(audit/'freeze.json');receipt=read(audit/'evaluation_receipt.json');pairs=read(audit/'pairs.json');archives=read(log/'T053A_archives.json');active=read(log/'T053A_active.json')
previous=read(log/'T053A_delivery.json') if (log/'T053A_delivery.json').exists() else {}
status=active['status'];m=s['metrics']
fig,axs=plt.subplots(1,2,figsize=(10,3.5))
for ax,key,label in zip(axs,['delta_psnr','delta_ssim'],['Paired PSNR change (dB)','Paired RGB-SSIM change']):
 ax.plot(range(1,101),sorted(row[key] for row in pairs));ax.axhline(0,color='black',lw=.6);ax.set(xlabel='Image rank (each curve sorted independently)',ylabel=label);ax.grid(alpha=.2)
fig.suptitle('T053 additive range closure vs T052 — REFERENCE_ORACLE_ONLY');fig.tight_layout()
for ext in ['png','pdf']:fig.savefig(result/('paired_range.'+ext),dpi=170)
plt.close(fig)
lines=[f"# T053-A {status} — fixed additive-range closure",'', 'REFERENCE_ORACLE_ONLY. Zero deployable changes; zero official-test access.','',s['classification'],'','| Metric | T052 mean | T053 mean | T052 median | T053 median |','|---|---:|---:|---:|---:|']
for key in ['psnr','ssim']:lines.append(f"| {key} | {m['t052_'+key]['mean']:.12f} | {m[key]['mean']:.12f} | {m['t052_'+key]['median']:.12f} | {m[key]['median']:.12f} |")
lines+=['','Paired changes: `'+json.dumps({key:m[key] for key in ['delta_psnr','delta_ssim']})+'`. Sole gate: meanPSNR>=.50dB AND medianPSNR>=.25dB AND meanSSIM>=0.','', 'Win/equal/loss: `'+json.dumps(s['win_equal_loss'])+'`.','', '![Paired changes](T053A_result/paired_range.png)','', '## Fixed experiment and provenance','',f"Scientific source {active['source']}; branch{active['branch']}; base2433dd70db158d50b7728e4750d33f81b0a95141. Accepted T052 scientific sourcedeployment e3bbf12c701d642a215afc049ca05cf9017feed1, evidence86dde41c3b795b78217172583e64b6ab3f2b2d50. T052 freeze83ebd03b57e4c5e43191194bc66d507f56090ed593d9681d140ffa29b4e3baa8; pairsb0c571e305f28e30b4acbe9b1dc0e7d3b06b5fc577f266fcf5d42641368555ff; configf3e4a3b7e3c0b9225b1fa2a673c6b1088b4a2fd3cfd03827f1957d2a60408522. Cohortb88c8347005984b5523b117b52c0c068672fe172eb7c9aa5b60102d350e2d85b. T053A_source_binding.json contains80 exactsourcehashes verified beforedeployment andpersistedinpreflight/config. The accepted single-rounding verifier is included in this tested T053 manifest; no post-run verifier change.",'', 'ReuseT052renderer; exactselectedu+bstarts. Convertu toimmutablebuffer; allpreT052rawEV/gamma/gain/lift/q andhardgate frozen. Onlyb[1,1,8,8] trainable. RGBsharedphysicalcontrols bilinearalign_corners=False; fixedexposuree=bilinear(2tanh(u)); clamp(z_affine*2**e+b,0,1) thenfrozentone/hardgate, original lowoutsideactive. FreshAdam.01, bprojection[-.4,.4]aftereachupdate, exactly500updates/oneacceptedstart/501states; earlieststrictfullRGBMSEminimum. Float32renderer/float64loss;A6000GPU1,seed7,TF32off,threads1.','',f"All100 low-only T052 reconstruction completed{pre['completed_utc']}, maxerror{pre['all100_max_abs']}, bitexact{pre['all100_bit_exact']}, normals0, preflightSHA{active['preflight_sha256']}. Firstnormal{freeze['opened'][1]['utc']}; all100selectedoutputs frozen{freeze['completed_utc']} SHA{receipt['freeze_sha256']} beforefirstmetricdecode{receipt['normal_opens'][0]['utc']}.",'', 'Exactcommands/envs/logs in resultpack. Runs: `'+json.dumps({key:active[key] for key in ['release','preflight_run','oracle_run','evaluation_run']})+'`.','',f"Tests: unchangedbaseline3passed30.51s; localfocused+affected5passed19.55s;server5passed2.49s;compilePASS. All100preflight{pre['seconds']:.6f}s; oracle{s['runtime_seconds']:.6f}s. Preflight/oracle/evaluation/replayexit0.",'','## Starting and selected additive distributions','', 'Physicalcontrol distributions cover all6400controls. Full-resolution field distributions cover23520000activepixels, where the correction is applied. Exact hits are equality to float32 +/-0.20 and +/-0.40, not counts exceeding the oldbound.']
for key,values in s['b_distributions'].items():lines+=['',key+': `'+json.dumps(values)+'`.']
lines+=['','Beststep histogram: `'+json.dumps(s['best_step_histogram'])+'`; at500: '+str(s['at_step500'])+'/100.','','## Independent replay and limits','', '`'+json.dumps(replay)+'`','', 'Independent NumPy single-rounding half-pixel interpolation checks frozenexposure plusstarting/selectedadditivefields. Savedexactfields are used only afterinterpolationverification forfloat32renderer reconstruction with independentaffine/NumPytone arithmetic. Check all50100bstates finite/bounds/exactacceptedstarts/earliestminima; u/raw/lift/q/knots/evbitexact; inactiveoutputsoriginal; frozenfilehashes;200metrics; allpaireddeltas/distributions/summaries. Renderer/interpolation1e-6 andscalar1e-10tolerances unchanged.','', 'Failures/infrastructure deviations: `'+json.dumps(active['failures'])+'`. ExistingNVMLandprotobufwarningsnonblocking. No scientificfailure, settingschange, sweep, or experimentrestart.','', 'Reference-only finite-budget development diagnostic, not deployable performance, heldoutSOTA or a certifiedoptimum. No target/oraclegradient/state/metric enters deployableTTT. No newcohort, baseline rerun or officialtest. AcceptedT052dependency retained without PRhistorycleanup/selfmerge.','', 'Archives: `'+json.dumps(archives)+'`. FulloutputsremoteF, compacthistories/plots/receiptsprojectlocal.','',active['next_step']]
(log/'T053A_report.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
delivery=previous.copy();delivery.update(status=status,completed_utc=previous.get('completed_utc',datetime.datetime.now(datetime.timezone.utc).isoformat()),tested_source=active['source'],pr=active['pr'],summary=s,replay=replay,archives=archives,runs={key:active[key] for key in ['release','preflight_run','oracle_run','evaluation_run']},failures=active['failures'],scientific_deviations=[],label='REFERENCE_ORACLE_ONLY',official_test_access=False,next_step=active['next_step'])
(log/'T053A_delivery.json').write_text(json.dumps(delivery,indent=2)+'\n',encoding='utf8')
