from pathlib import Path
import json,datetime
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
p=Path('research_log');r=p/'T044A_result'
f=json.loads((r/'stage_a/freeze.json').read_text());s=json.loads((r/'stage_b/summary.json').read_text());receipt=json.loads((r/'stage_b/receipt.json').read_text());replay=json.loads((r/'stage_b/independent_replay.json').read_text());pairs=json.loads((r/'stage_b/pairs.json').read_text());archives=json.loads((p/'T044A_archives.json').read_text())
fig,ax=plt.subplots(figsize=(8,5))
for loss,label,color in [(False,'No PSNR loss (71)','#247d49'),(True,'PSNR loss (29)','#c44c22')]:
    rows=[x for x in pairs if x['loss']==loss];ax.scatter([x['D_legacy'] for x in rows],[x['delta_psnr'] for x in rows],label=label,c=color,s=30,alpha=.8)
ax.axhline(0,color='black',lw=.8);ax.set(xlabel='Frozen low-only legacy displacement',ylabel='T036 minus T026 PSNR (dB)',title=f"Risk AUC {s['roc_auc']:.3f}; Spearman {s['spearman']:+.3f}");ax.legend();ax.grid(alpha=.15);fig.tight_layout()
for ext in ['png','pdf']:fig.savefig(r/f'legacy_displacement.{ext}',dpi=170)
lines=['# T044-A: target-free legacy-extrapolation score association audit','',
f"**{s['classification']}**. The fixed risk direction fails both predeclared conditions: ROC-AUC **{s['roc_auc']:.15f} < 0.75**, Spearman **{s['spearman']:+.15f} > -0.35**. Exactly **29 loss / 71 non-loss** cases reproduce the accepted T036 split. Larger legacy excursion associates with greater paired PSNR improvement here, rather than the hypothesized risk. This is a descriptive association on an already-reference-used cohort, not a causal claim or a deployable rule.",'',
'## Scope and physical scalar','',
'Same accepted T036 100 images, frozen Region2 gate, fixed anchor step 10 and each accepted selected common-gain state. No state reselection or gate recomputation. For each active region, d_EV=(EV_selected-EV_step10)/4 and d_gamma=log2(gamma_selected/gamma_step10)/2. D_legacy is sqrt(mean of the squared 2K coordinates), K=active region count. Zero active => 0; actual zero-active images: **0**. Gain is excluded. No image, renderer forward, model, optimizer, threshold or controller is used. The accepted mapping `ttie.isp.physical_parameters` is unchanged: EV=2*tanh(raw_EV), gamma=exp(log(2)*tanh(raw_gamma)); evaluate this same function in float64 from immutable float32 states to make the scalar reproducible. The main score is checked against accepted common-gain physical_grid in a focused test.','',
'## Pre-label bindings and information boundary','',
f"Cohort SHA `{f['cohort_sha256']}`; accepted T036 freeze SHA `{f['prior_freeze_sha256']}`. Original trajectory root `{f['accepted_root']}`. For every image, scores.json records decision/trajectory file hashes, canonical frozen gate hash, full and legacy-only anchor/selected tensor hashes, selected index, active mask and score. states.pt contains exact frozen anchor/selected snapshots and gates. Source binding pins all imported repository code plus the scalar/statistics/replay implementation; binding SHA `{f['source_binding_sha256']}`.",'',
f"All **100 scores** persisted at **{f['completed_utc']}**, freeze SHA `{receipt['stage_a_freeze_sha256']}`, score-table SHA `{f['scores_sha256']}`, raw-snapshot SHA `{f['states_sha256']}`. First metric attachment **{receipt['metric_open_utc']}**, strictly later. Stage A has no metric/normal/reference-gradient/loss-ID inputs or imports; its file hook logs original-artifact reads and rejects any original audit filename outside freeze/config/decision/trajectory, and rejects image opens. Zero normal, prior metric, prior reference-gradient or loss-ID opens before freeze. Stage B only reads accepted `metrics.csv`, SHA `{receipt['metric_sha256']}`, checks identities/selected steps and exact common-minus-baseline PSNR deltas. Neither stage opens normals. No fresh cohort or official-test access.",'',
'## Paired association results','',
'| Group | N | Mean D | Q25 | Median D | Q75 |','|---|---:|---:|---:|---:|---:|']
for name,g in s['groups'].items():lines.append(f"| {name} | {g['count']} | {g['mean']:.12f} | {g['q25']:.12f} | {g['median']:.12f} | {g['q75']:.12f} |")
lines+=['', '![Frozen legacy displacement and paired PSNR](T044A_result/legacy_displacement.png)','',
'AUC treats larger D as greater risk, using average ranks and half-credit for ties. Spearman uses average ranks and their centered correlation; no p-value gate. Quartiles use linear interpolation. No bootstrap, cutoff, inverted score, alternative norm or combined signal was tested.','',
'| Score tail | Image | D_legacy | Paired PSNR delta |','|---|---|---:|---:|']
for key in ['smallest','largest']:
    for row in s[key]:lines.append(f"| {key} | {row['low']} | {row['D_legacy']:.12f} | {row['delta_psnr']:+.12f} |")
lines+=['','## Execution and independent replay','',
f"Tested source **ba2f1b26e2d09e0eafb3f33b3ed8e078c5d3cd83**, branch `codex/T044A-legacy-drift`, PR https://github.com/word-ky/TTIE/pull/69. Release `20260915-152431-ttie-t044a-audit-fixed`. Stage A run `20260915-152458-ttie-t044a-stage-a`, score generation {f['seconds']:.9f}s. Stage B run `20260915-152656-ttie-t044a-stage-b`, association {receipt['seconds']:.9f}s, independent replay {replay['seconds']:.9f}s. Both actual executions exit0; light CPU state arithmetic, no GPU model work was needed. Exact commands and single-thread environment are retained in both run/run.sh receipts.",'',
f"Independent replay imports no main T044 score/statistics/verdict helper. It reloads original hash-bound trajectories/decisions and frozen snapshots, checks every gate and state is exact, reconstructs physical EV/gamma with Python math, recomputes all100 scores, AUC via all **2059** positive/negative pairs, Spearman with explicit tie ranks and math.fsum, paired deltas, descriptive summaries and tail identities. **{replay['scalar_checks']} scalar checks**, max discrepancy **{replay['max_abs_error']:.16g} <=1e-10**, final verdict exact, PASS. Independent replay also checks freeze precedes metric attachment.",'',
'Baseline renderer test: 1 passed in12.37s. New local tests: 2 passed in10.41s; server tests: 2 passed in2.35s. Tests cover physical mapping, active masks, zero-active case, gain exclusion, tied AUC/Spearman and both verdict boundaries.','',
'## Failures, deviations, artifacts and next step','',
'Preparation: initial sparse-checkout add command used an unsupported option, leaving a test dependency absent; corrected sparse inclusion, then baseline passed. Two local test processes aborted inside NumPy cov/corrcoef called by scipy spearmanr, including a single-thread retry. Replaced covariance with the algebraically equivalent explicit centered-rank sums; local and server tests pass. Initial source b4e322d and release152254 were superseded before any experimental run or metric access. Report generation also had one unterminated string, corrected before rendering. These are implementation/environment repairs, with no scientific definition or threshold change.','',
'SSH connection timed out once during each stage launch, before either process started. Checked absence of tmux/logs before resuming: Stage A reused its exact generated run.sh; Stage B reconstructed the same wrapper from the persisted command in meta.json. Each scientific stage ran exactly once; no partial score or label computation preceded these recoveries. No scientific deviations, optimizer updates, state/selection changes, rerendering, fresh cohort, normal opens or official-test access.','',
f"Evidence archive {archives['bytes']} bytes, SHA `{archives['sha256']}`, verified locally and under both home/F `shared/t044a`. Contains score freeze, exact raw snapshots/gates, paired table, statistics, independent replay and both run logs. Original T036 trajectories remain unchanged. Source and evidence are delivered by PR; a single completion report is appended directly to the main Codex mailbox. Project-local reports/plots/recovery are retained under research_log.",'',
'Stop after this association audit. The predeclared large-excursion risk hypothesis is unsupported and the observed association points the other way; do not turn D into a trust radius, invert it, fit a threshold or implement a controller in this cycle. Research lead should reassess why productive legacy movement and local field unreliability coexist before specifying another intervention.','',s['classification']]
(p/'T044A_report.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
d=dict(status='DONE',completed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),executed_source='ba2f1b26e2d09e0eafb3f33b3ed8e078c5d3cd83',branch='codex/T044A-legacy-drift',pr='https://github.com/word-ky/TTIE/pull/69',stage_a_run='20260915-152458-ttie-t044a-stage-a',stage_b_run='20260915-152656-ttie-t044a-stage-b',classification=s['classification'],roc_auc=s['roc_auc'],spearman=s['spearman'],replay=replay,archives=archives,tests={'baseline':'1passed12.37s','local':'2passed10.41s','server':'2passed2.35s'},failures=['Sparse test dependency initially absent; corrected','Two local NumPy covariance aborts; equivalent explicit rank sums pass','Two SSH launch timeouts before actual execution; resumed persisted commands once each'],scientific_deviations=[],optimizer_updates=0,selection_changes=0,official_test_access=False,next_step='Stop; await research-lead review; no controller/score inversion/threshold.')
(p/'T044A_delivery.json').write_text(json.dumps(d,indent=2)+'\n')
