"""Hash-committed storage for already-frozen ``<row>_plus_D`` control rows (disk; orchestrator request 2026-09-27).

A ``_plus_D`` output is D(frozen source output) (research_log/T075A/v2/denoise_d.py). Tensors are deterministic;
the .gz file bytes additionally depend on the gzip header (MTIME, FNAME), which this tool records per image, so files
can be regenerated byte for byte.

    strip   --outputs ROW --source-dir SRC [--workers 4]
        For every image: check the file SHA256 and tensor SHA256 against the frozen manifest; regenerate the file in
        memory from the frozen source (D + same gzip header) and require byte equality with the file on disk. Only if
        every image passes: write ROW/regen_record.json (+ REGENERATE.md), then delete the output.pt.gz files.
        decision.json / output_manifest.json stay; freeze + verification JSONs are untouched.
    restore --outputs ROW --source-dir SRC [--workers 4]
        Regenerate every missing output.pt.gz and require file SHA256 == frozen manifest (fails closed otherwise).
Run ``restore`` before any metric run or gate re-validation that re-hashes the output files.
"""

import argparse
import gzip
import io
import json
import struct
import sys
from multiprocessing import get_context
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import denoise_d as dd  # noqa: E402

NOTE = """# Hash-committed `_plus_D` control row

The output tensors of this row were deleted to save disk after metrics were computed (orchestrator request,
2026-09-27). Every image's output is D(frozen source output) with `denoise_d.py` (NLM, h = 6·255·σ̂). Per-image file
SHA256, tensor SHA256 and gzip header fields are in `regen_record.json`; the frozen `output_manifest.json`,
`decision.json` files, freeze receipt and verification are unchanged.

Regenerate bit-exactly (fails closed on any hash difference):

    python research_log/T075A/v2/regenerate_plus_D.py restore --outputs <this dir> --source-dir <frozen source row dir>

The source row is `{source}` (frozen manifest `{source_sha}`).
"""


def gzip_header(raw):
    dd.fail(raw[:3] == b"\x1f\x8b\x08", "not a gzip/deflate file")
    flg = raw[3]
    dd.fail(flg & ~0x08 == 0, f"unsupported gzip flags {flg}")
    mtime = struct.unpack("<I", raw[4:8])[0]
    name = ""
    if flg & 0x08:
        end = raw.index(b"\x00", 10)
        name = raw[10:end].decode("latin-1")
    return {"mtime": mtime, "fname": name, "xfl": raw[8], "os": raw[9]}


def gzip_bytes(tensor, header):
    import torch

    buf = io.BytesIO()
    with gzip.GzipFile(filename=header["fname"], mode="wb", fileobj=buf, compresslevel=1, mtime=header["mtime"]) as stream:
        torch.save(tensor, stream)
    data = buf.getvalue()
    dd.fail(data[8] == header["xfl"] and data[9] == header["os"], "gzip XFL/OS byte differs")
    return data


def _regen(task):
    import torch

    torch.set_num_threads(1)
    mode, out_dir, source_dir, row, source_row, header = task
    stem = Path(row["low_name"]).stem
    source, source_file_sha = dd.load_tensor(Path(source_dir) / stem / "output.pt.gz")
    dd.fail(source_file_sha == source_row["output_file_sha256"] == row["source_output_file_sha256"], f"source file {stem}")
    tensor, facts = dd.apply_d(source)
    dd.fail(dd.tensor_sha256(tensor) == row["output_tensor_sha256"] and facts["h"] == row["h"], f"regenerated tensor {stem}")
    path = Path(out_dir) / stem / "output.pt.gz"
    if mode == "strip":
        raw = path.read_bytes()
        dd.fail(dd.sha256_bytes(raw) == row["output_file_sha256"], f"file SHA before strip {stem}")
        header = gzip_header(raw)
        dd.fail(gzip_bytes(tensor, header) == raw, f"in-memory regeneration differs from the file {stem}")
        return {"low_name": row["low_name"], "output_file_sha256": row["output_file_sha256"],
                "output_tensor_sha256": row["output_tensor_sha256"], "gzip": header, "bytes": len(raw)}
    if path.exists():
        dd.fail(dd.sha256_file(path) == row["output_file_sha256"], f"existing file differs {stem}")
        return 0
    data = gzip_bytes(tensor, header)
    dd.fail(dd.sha256_bytes(data) == row["output_file_sha256"], f"regenerated file SHA differs {stem}")
    path.write_bytes(data)
    return 1


def _load(outputs, source_dir):
    outputs, source_dir = Path(outputs), Path(source_dir)
    manifest = json.loads((outputs / "output_manifest.json").read_bytes())
    dd.fail(manifest["method_id"].endswith("_plus_D"), "only <row>_plus_D control rows")
    dd.fail(dd.sha256_file(source_dir / "output_manifest.json") == manifest["source_output_manifest_sha256"], "source manifest binding")
    source = json.loads((source_dir / "output_manifest.json").read_bytes())
    return outputs, source_dir, manifest, source


def strip(outputs, source_dir, workers=4):
    outputs, source_dir, manifest, source = _load(outputs, source_dir)
    tasks = [("strip", str(outputs), str(source_dir), r, s, None) for r, s in zip(manifest["rows"], source["rows"])]
    with get_context("spawn").Pool(workers) as pool:
        images = pool.map(_regen, tasks, chunksize=1)
    record = {"output_manifest_sha256": dd.sha256_file(outputs / "output_manifest.json"), "method_id": manifest["method_id"],
              "source_row": manifest["source_row"], "source_output_manifest_sha256": manifest["source_output_manifest_sha256"],
              "tool": "research_log/T075A/v2/regenerate_plus_D.py", "tool_sha256": dd.sha256_file(__file__),
              "denoise_d_sha256": dd.sha256_file(dd.__file__), "images": images}
    (outputs / "regen_record.json").write_text(json.dumps(record, indent=2))
    (outputs / "REGENERATE.md").write_text(NOTE.format(source=manifest["source_row"], source_sha=manifest["source_output_manifest_sha256"]))
    freed = 0
    for item in images:
        path = outputs / Path(item["low_name"]).stem / "output.pt.gz"
        freed += path.stat().st_size
        path.unlink()
    return {"row": str(outputs), "files": len(images), "freed_bytes": freed}


def restore(outputs, source_dir, workers=4):
    outputs, source_dir, manifest, source = _load(outputs, source_dir)
    record = json.loads((outputs / "regen_record.json").read_bytes())
    dd.fail(record["output_manifest_sha256"] == dd.sha256_file(outputs / "output_manifest.json"), "manifest changed since strip")
    headers = {i["low_name"]: i["gzip"] for i in record["images"]}
    tasks = [("restore", str(outputs), str(source_dir), r, s, headers[r["low_name"]]) for r, s in zip(manifest["rows"], source["rows"])]
    with get_context("spawn").Pool(workers) as pool:
        written = sum(pool.map(_regen, tasks, chunksize=1))
    return {"row": str(outputs), "restored": written}


def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("command", choices=["strip", "restore"])
    p.add_argument("--outputs", type=Path, required=True)
    p.add_argument("--source-dir", type=Path, required=True)
    p.add_argument("--workers", type=int, default=4)
    a = p.parse_args()
    dd.fail(a.workers <= 6, "at most 6 workers")
    print(json.dumps((strip if a.command == "strip" else restore)(a.outputs, a.source_dir, a.workers)), flush=True)


if __name__ == "__main__":
    main()
