import json,pathlib,datetime
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
log=pathlib.Path(__file__).resolve().parents[1];result=log/'T054A_result';audit=result/'audit'
def read(p):return json.loads(p.read_bytes())
s=read(audit/'summary.json');replay=read(audit/'independent_replay.json');pre=read(result/'preflight/preflight.json');freeze=read(audit/'freeze.json');receipt=read(audit/'evaluation_receipt.json');pairs=read(audit/'pairs.json');archives=read(log/'T054A_archives.json');active=read(log/'T054A_active.json')
previous=read(log/'T054A_delivery.json') if (log/'T054A_delivery.json').exists() else {}
status=active['status'];m=s['metrics']
fig,axs=plt.subplots(1,2,figsize=(10,3.5))
for ax,key,label in zip(axs,['delta_psnr','delta_ssim'],['Paired PSNR change (dB)','Paired RGB-SSIM change']):
 ax.plot(range(1,101),sorted(row[key] for row in pairs));ax.axhline(0,color='black',lw=.6);ax.set(xlabel='Image rank (each curve sorted independently)',ylabel=label);ax.grid(alpha=.2)
fig.suptitle('T054 local detail vs T052 — REFERENCE_ORACLE_ONLY');fig.tight_layout()
for ext in ['png','pdf']:fig.savefig(result/('paired_detail.'+ext),dpi=170)
plt.close(fig)
lines=[f'# T054-A {status} — fixed local-detail probe','','REFERENCE_ORACLE_ONLY. Zero deployable changes; zero official-test access.','',s['classification'],'','| Metric | T052 mean | T054 mean | T052 median | T054 median |','|---|---:|---:|---:|---:|']
for key in ['psnr','ssim']:lines.append(f"| {key} | {m['t052_'+key]['mean']:.12f} | {m[key]['mean']:.12f} | {m['t052_'+key]['median']:.12f} | {m[key]['median']:.12f} |")
lines+=['','Paired deltas: `'+json.dumps({k:m[k] for k in ['delta_psnr','delta_ssim']})+'`. Sole gate: mean PSNR >= .50 dB, median >= .25 dB, and mean RGB-SSIM >= .020.','', 'Win/equal/loss: `'+json.dumps(s['win_equal_loss'])+'`.','','![Paired changes](T054A_result/paired_detail.png)','','## Fixed experiment and provenance','',f"Tested source {active['source']}; base2433dd70db158d50b7728e4750d33f81b0a95141; branch {active['branch']}. Accepted T052 source e3bbf12c701d642a215afc049ca05cf9017feed1 / evidence86dde41c3b795b78217172583e64b6ab3f2b2d50. No T053 states imported. T052 freeze83ebd03b57e4c5e43191194bc66d507f56090ed593d9681d140ffa29b4e3baa8; pairsb0c571e305f28e30b4acbe9b1dc0e7d3b06b5fc577f266fcf5d42641368555ff; configf3e4a3b7e3c0b9225b1fa2a673c6b1088b4a2fd3cfd03827f1957d2a60408522. Cohortb88c8347005984b5523b117b52c0c068672fe172eb7c9aa5b60102d350e2d85b. T054A_source_binding.json binds80 exact Git blobs, persisted unchanged in preflight/config.",'','Frozen T052 output y0; D=y0-B(y0). B applies [1,4,6,4,1]/16 horizontally then vertically, reflect padding two pixels, independent RGB, fixed float32 weighted slice sums. Analytic tests: RGB impulse gives outer-product kernel, constant image preserved exactly, reflected boundary ramp gives 3/64 at left edge. Detail basis is checked against analytic impulse residual.','', 'Only raw v[1,1,8,8] is trainable, zero initialized. c=tanh(bilinear(v, align_corners=False)); interpolation BEFORE tanh follows the raw-grid field wording and is explicitly tested against the alternative order. Selected controls are tanh(v_grid) for description. y=clamp(y0+cD,0,1) on frozen active mask, y0 exactly on inactive pixels. Fresh Adam .05, exactly500 updates, one zero start, states0..500 and earliest strict MSE minimum. Float32 renderer / float64 full-RGB MSE. All prior raw/lift/q/u/b/knots/EV and hard gate frozen; y0/D buffers immutable. A6000 GPU1, TF32off, threads1.','',f"All100 low-only reconstructions completed {pre['completed_utc']}, max error {pre['all100_max_abs']}, all bit-exact {pre['all100_bit_exact']}, normal decodes0. Preflight SHA{active['preflight_sha256']}. First reference {freeze['opened'][1]['utc']}; all100 selected outputs frozen {freeze['completed_utc']} SHA{receipt['freeze_sha256']}; first metric decode {receipt['normal_opens'][0]['utc']}.",'', 'Runs: `'+json.dumps({k:active[k] for k in ['release','preflight_run','oracle_run','evaluation_run']})+'`. Exact commands/env/logs in compact result pack.','',f"Tests: baseline3passed17.56s, localfocused+affected6passed13.85s, server6passed2.46s. CompilePASS. Preflight{pre['seconds']:.9f}s; oracle{s['runtime_seconds']:.9f}s. All jobs exit0.",'','## Selected coefficient distributions','','Controls include all6400 grid values after tanh; full field includes all24000000 pixels, including inactive locations where coefficients are ignored. Exact ±1 hits use float32 equality.']
for k,v in s['c_distributions'].items():lines+=['',k+': `'+json.dumps(v)+'`.']
lines+=['','Best-step histogram: `'+json.dumps(s['best_step_histogram'])+'`; step500: '+str(s['at_step500'])+'/100.','','## Independent replay','','`'+json.dumps(replay)+'`','','NumPy/SciPy verifier independently reconstructs blur with float64 convolve1d mirror padding, raw-grid half-pixel interpolation with accepted single-rounding coordinates, tanh coefficient, and float32 renderer. Saved exact c/D are used only after independent basis/interpolation checks to isolate final renderer rounding. Accepted fixed y0 is hash-verified; the preceding all100 low-only preflight reconstructs the complete T052 renderer. All50100 states checked for shape/finite/zero initialization, earliest selection and unchanged older coordinates;200 metrics recomputed independently. Tolerances unchanged: basis/interpolation/renderer1e-6, scalar1e-10.','','Failures/deviations: `'+json.dumps(active['failures'])+'`. No scientific changes or reruns. Existing NVML/protobuf warnings are nonblocking.','','This is a finite-budget development reference capacity diagnostic, not deployable TTT, held-out SOTA or a certified optimum. No target/gradient/state/metric enters deployable TTT; official test remains sealed. Accepted unmerged T052 history retained as instructed.','','Archives: `'+json.dumps(archives)+'`. Full selected outputs remain remote/F; compact histories and evidence are project-local.','',active['next_step']]
(log/'T054A_report.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
delivery=previous.copy();delivery.update(status=status,completed_utc=previous.get('completed_utc',datetime.datetime.now(datetime.timezone.utc).isoformat()),tested_source=active['source'],pr=active['pr'],summary=s,replay=replay,archives=archives,runs={k:active[k] for k in ['release','preflight_run','oracle_run','evaluation_run']},failures=active['failures'],scientific_deviations=[],label='REFERENCE_ORACLE_ONLY',official_test_access=False,next_step=active['next_step'])
(log/'T054A_delivery.json').write_text(json.dumps(delivery,indent=2)+'\n',encoding='utf8')
