import pathlib,sys,json,hashlib,torch,numpy as np
out=pathlib.Path(sys.argv[1]);r=json.loads((out/'result.json').read_text());mark=r['marker'];pm=r['prediction_marker'];sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();torch.set_num_threads(1);assert all(sha(n)==v for n,v in r['inputs_before'].items()) and r['inputs_before']==r['inputs_after'];assert sha(out/'vectors.pt')==mark['vectors_sha256'] and sha(out/'maps.pt')==mark['maps_sha256'];assert sha(out/'predictions.pt')==pm['predictions_sha256'] and sha(out/'evaluation_rows.pt')==r['evaluation_rows_sha256'];parent=json.loads(pathlib.Path(next(n for n in mark['inputs'] if n.endswith('/T059E/split.json'))).read_text());norm=json.loads(pathlib.Path(next(n for n in mark['inputs'] if n.endswith('/normalization.json'))).read_text())['values'];manifest=pathlib.Path(next(n for n in mark['inputs'] if n.endswith('/training_manifest.json')));banks=json.loads(manifest.read_text());split=mark['split'];ordered=sorted(parent['image_ids']['train'],key=lambda i:parent['group_indices'][str(i)]);assert split['image_ids']['selector']==ordered[5::6] and len(split['image_ids']['fit'])==40;vectors=torch.load(out/'vectors.pt',weights_only=True,map_location='cpu');nn=torch.load(out/'maps.pt',weights_only=True,map_location='cpu');saved=torch.load(out/'evaluation_rows.pt',weights_only=True,map_location='cpu');pred=torch.load(out/'predictions.pt',weights_only=True,map_location='cpu');data={}
for side in ['fit','selector']:
 ids=split['row_indices'][side];assert ids==[i for i in parent['row_indices']['train'] if parent['canonical'][i]['image_id'] in split['image_ids'][side]];xs=[];ys=[]
 for bi in split['bank_indices'][side]:
  root=manifest.parent/banks[bi]['directory'];assert str(root/'bank.pt') in r['inputs_before'] and str(root/'targets.json') in r['inputs_before'];xs.append(torch.load(root/'bank.pt',weights_only=True,map_location='cpu')['features']);ys.extend(v['mse'] for v in json.loads((root/'targets.json').read_text()))
 x=torch.cat(xs);rec=[parent['canonical'][i] for i in ids];bank=np.array([v['bank_index'] for v in rec]);state=np.array([v['state_index'] for v in rec]);images=np.array([v['image_id'] for v in rec]);a=np.empty(len(ids),dtype=np.int64)
 for bi in np.unique(bank):
  z=np.flatnonzero((bank==bi)&(state==0));assert len(z)==1;a[bank==bi]=z[0]
 mean=torch.tensor(norm['x_mean']);scale=torch.tensor(norm['x_scale'])
 if side=='fit':
  assert torch.equal(x.double().mean(0).float(),mean);v=x.double().std(0,unbiased=False);assert torch.equal(torch.where(v==0,torch.ones_like(v),v).float(),scale)
 u=(x.numpy()-mean.numpy())/scale.numpy();u0=u[a];z=np.concatenate([u-u0,u0],axis=1)
 for k,v in [('anchor',a),('anchor_global',np.array(ids)[a]),('u',u),('u0',u0),('z',z),('global_index',np.array(ids)),('image',images)]:assert np.array_equal(v,vectors[side][k].numpy())
 log=(torch.tensor(ys,dtype=torch.float64)+1e-6).log();t=(log.float()-torch.tensor(norm['y_mean']))/torch.tensor(norm['y_scale']);dt=t-t[torch.from_numpy(a)];data[side]=dict(z=z.astype(np.float64),target=dt,images=images,globals=np.array(ids))
metrics={};errors={};tr=data['fit'];assert np.all(tr['globals'][:-1]<tr['globals'][1:])
for side,q in data.items():
 err=0
 for start in range(0,len(q['z']),32):
  d=np.square(q['z'][start:start+32,None,:]-tr['z'][None,:,:]).sum(-1);allowed=(q['images'][start:start+32,None]!=tr['images'][None,:]) if side=='fit' else np.ones(d.shape,dtype=bool);d[~allowed]=np.inf;idx=d.argmin(1);v=d[np.arange(len(idx)),idx];sl=slice(start,start+len(idx));assert np.array_equal(idx,nn[side]['index'][sl].numpy());assert np.array_equal((d==v[:,None]).sum(1),nn[side]['tie_count'][sl].numpy());assert np.array_equal(allowed.sum(1),nn[side]['candidate_count'][sl].numpy());actual=nn[side]['distance'][sl].numpy();assert np.allclose(v,actual,rtol=1e-12,atol=1e-12);err=max(err,float(np.abs(v-actual).max()))
 idx=nn[side]['index'];assert np.array_equal(tr['globals'][idx.numpy()],nn[side]['global_index'].numpy());assert np.array_equal(tr['images'][idx.numpy()],nn[side]['image'].numpy());assert not (q['images']==tr['images'][idx.numpy()]).any();p=tr['target'][idx];assert torch.equal(p,pred[side]) and torch.equal(p,saved[side]['pred']) and torch.equal(q['target'],saved[side]['target']);v=np.abs(p.numpy()-q['target'].numpy());loss=np.where(v<1,np.float32(.5)*v*v,v-np.float32(.5));assert np.array_equal(loss,saved[side]['loss'].numpy());h=float(torch.from_numpy(loss).mean());assert h==r['statistics'][side]['huber'];metrics[side]=h;errors[side]=err
 for kind in ['bank','image']:
  ids=vectors[side][kind]
  for group in r['statistics'][side]['per_'+kind]:assert group['huber']==float(saved[side]['loss'][ids==group['id']].mean())
limit=.07650849781930447;label='explicit anchor-context 56-D locality fails the source control; stop' if metrics['fit']>limit else 'explicit bank-anchor context is insufficient for source-image scalar localization under fixed 1-NN' if metrics['selector']>limit else 'explicit bank-anchor context restores source-selector scalar locality under fixed 1-NN; context-conditioned representation is supported for a later parametric test';assert label==r['classification'];assert mark['persisted_utc']<pm['fit_access']['opened_utc']<pm['persisted_utc']<r['selector_access']['opened_utc'];assert all(v==0 for v in r['counters'].values());z=dict(verification='PASS',all4357_vectors_distances_ties_neighbors_predictions_losses_verified=True,per_image_and_bank_metrics_verified=True,huber=metrics,max_distance_error=errors,classification=label,result_sha256=sha(out/'result.json'));(out/'verification.json').write_text(json.dumps(z,indent=2));print(json.dumps(z))
